//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaQuestionEditor_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaQuestionEditor_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///  &lt;title&gt;Markdown Editor&lt;/title&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot;&gt;
        ///  &lt;style&gt;
        ///    html,
        ///    body {
        ///      display: flex;
        ///      flex-direction: column;
        ///      height: 100vh;
        ///      margin: 0;
        ///    }
        ///
        ///    #codeedit {
        ///      flex-grow: 1;
        ///    }
        ///  &lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Oxygen&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        div, h1, h2, h3, h4, h5, h6 {
        ///            font-family: &apos;Oxygen&apos;, sans-serif;
        ///        }
        ///
        ///        img {
        ///            max-width: 70%;
        ///            max-height: 70%;
        ///            vertical-align: top;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/markdown-it/11.0.0/markdown-it.min.js&quot;
        ///            integrity=&quot;sha512-0tDdhRf9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
    }
}
