name: 'Build'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Restore NuGet Packages
        run: nuget restore DeltaEditor.sln

      - name: Build App
        run: msbuild DeltaEditor.sln /p:Configuration=Debug /p:Platform=x64
